--CREATE PROCEDURE NOTLISTESI
--AS
--SELECT NOTID,AD +' '+ SOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,
--ORTALAMA,DURUM FROM TBLNOTLAR
--INNER JOIN TBLOGRENCÝ ON TBLNOTLAR.OGR=TBLOGRENCÝ.ID
--INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS

execute NOTLISTESI
